### ISSUE TITLE
Build issue under Linux- folder name

### ISSUE THREAD

**Issue by brunofletcher** [sparkfun/SparkFun_Pro_Micro-ESP32C3#5]
Good evening. The build fails on case-sensitive operating system, such as Linux when using the Arduino IDE.  

The following variable defined in "sparkfun_boards.txt":

sparkfun_pro_micro_esp32c3.build.variant=sparkfun_pro_micro_esp32c3

Needs to be changed to:

sparkfun_pro_micro_esp32c3.build.variant=sparkFun_pro_micro_esp32c3

if we use your current directory structure.

Note that a directory named "sparkfun_pro_micro_esp32c3" is not the same as "sparkFun_pro_micro_esp32c3" for case-sensitive operating systems.

Another possible solution is to just need to rename the directory from sparkFun_pro_micro_esp32c3 (containing "pins_arduino.h") to sparkfun_pro_micro_esp32c3 (i.e., all lower case).

Cheers,
Bruno

**Comment by edspark** [comment]
Good morning,

Over the years I've developed some muscle memory when typing SparkFun. That's not intended to be camel case, and it's now been fixed.

Elias
